### ISSUE TITLE
Fastboot assets in build in non-fastboot app

### ISSUE THREAD

**Issue by Dhaulagiri** [jasonmit/ember-cli-moment-shim#146]
With 3.4.0 of this addon I'm seeing these files in my build even though I'm not in a fasboot app, is this expected?

 * `dist/moment/fastboot-moment.js`
 * `dist/moment/fastboot-moment-timezone.js`

**Comment by jasonmit** [comment]
@Dhaulagiri I have some ideas on how to remove this, but for now it is expected and harmless.  Will tackle after #145.

The patch will be to look for the presence of ember-cli-fastboot in the `project.addons` and otherwise return an empty public tree.

Update: actually, this would also solve for #145 so I will couple two issues together.
