### ISSUE TITLE
IncludedLocales is changing default locale

### ISSUE THREAD

**Issue by Kilowhisky** [jasonmit/ember-cli-moment-shim#21]
If i try and cherry pick my locale(s) as described in the documentation.

```
        moment: {
            includeLocales: ['es'],
        }
```

The default locale is set to 'es' not 'en'.   

If i switch it to 

```
        moment: {
            includeLocales: true,
        }
```

Then 'en' becomes the default again. 

apparently 

```
 includeLocales: ['en', 'es']
```

is not a valid option either. 

Suggestions?

**Comment by Kilowhisky** [comment]
Also i cannot just use an initializer to switch the locale because i'm using https://eonasdan.github.io/bootstrap-datetimepicker/ which initializes itself before ember initializers run.

**Comment by jasonmit** [comment]
`includeLocales` has nothing to do with setting the locale, it just makes the locale available within your application.  Useful for cherry picking the locales your application needs to support instead of bringing in the universe.

You still have to set the locale and that is documented here: https://github.com/jasonmit/ember-cli-moment-shim#configure-default-runtime-locale

> Also i cannot just use an initializer to switch the locale because i'm using https://eonasdan.github.io/bootstrap-datetimepicker/ which initializes itself before ember initializers run.

I don't think you even need to do it at the initializer level.  I imagine you are wrapping this jQuery plugin with an Ember component.  So, at the time your component is instantiated is when it should be evaluating your moment locale.

**Comment by sn3p** [comment]
Similar behaviour here:

``` js
moment: {
  includeLocales: ['en', 'nl', 'de']
}
```

This changes the default to `nl`, but would expect `en`.
But `includeLocales: true` sets the default to `en`.

Maybe because `en.js` doesn't exist as a locale?
https://github.com/moment/moment/tree/2.10.3/locale

**Comment by jasonmit** [comment]
@sn3p without digging in, I believe `en` is bundled by default so you don't need to provide it.  Though, I could be wrong... I can dig deeper soon.  Reopening to keep it on my radar or for anyone else to look into in the meantime.

**Comment by sn3p** [comment]
@jasonmit you're right that `en` is bundled (just tested).
But leaving it out from `includeLocales` still overwrites the default. Not a big deal because you can set the locale, but still unexpected behaviour I'd say.

**Comment by jasonmit** [comment]
So ember-cli-moment-shim does not do anything special around setting the default locale.  Momentjs liekly registers whatever registers locale data first as the default -- in this case it is `nl` since `en` is bundled already and is skipped.

This isn't something ember-moment/ember-cli-moment-shim handle automatically.  Setting the locale manually is what you'll want to do.  If you think there's a way to make the README clearer please submit the change and I'll be happy to merge.

Cross referencing w/ https://github.com/stefanpenner/ember-moment/issues/114
